"""A2A (Agent-to-Agent) JSON-RPC endpoints for WoTBot.

Implements the Google A2A protocol so any A2A-compatible agent can interact
with WoTBot — send messages, receive responses, and retrieve visualizations
as artifacts.

Endpoints:
  GET  /api/a2a/.well-known/agent-card  — Agent card (A2A standard)
  POST /api/a2a/jsonrpc                 — JSON-RPC 2.0 endpoint (methods:
                                          sendMessage, sendMessageStream)
  POST /api/a2a/message                 — Backward-compat simple message API
"""

from __future__ import annotations

import asyncio
import base64
import json
import logging
import os
from typing import Any, AsyncGenerator
from uuid import uuid4

import httpx
from fastapi import APIRouter, HTTPException, Request, UploadFile
from fastapi.responses import JSONResponse, Response, StreamingResponse
from pydantic import BaseModel

from wotbot.api.a2a_protocol import (
    JSONRPCRequest,
    JSONRPCResponse,
    JSONRPCError,
    SendMessageResult,
    TaskStatusUpdateEvent,
    Task,
    TaskState,
    TaskStatus,
    Role,
    Artifact,
    Part,
    wotbot_agent_card,
    make_image_part,
    make_message,
)
from wotbot.threads.runs import RunRegistry

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/a2a", tags=["a2a"])


# ---------------------------------------------------------------------------
# Backward-compat old request model
# ---------------------------------------------------------------------------


class Attachment(BaseModel):
    type: str = "text"
    data: str = ""
    contentType: str = ""
    displayName: str = ""


class A2AMessage(BaseModel):
    message: str
    threadId: str | None = None
    attachments: list[Attachment] = []


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


# Fallback for apps that mount this router without the main app's shared
# registry; a private registry still serializes A2A runs against each other.
_FALLBACK_RUN_REGISTRY = RunRegistry()


def _agent_graph(request: Request) -> Any | None:
    """Return the compiled LangGraph the app built during startup."""
    return getattr(request.app.state, "graph", None)


def _run_registry(request: Request) -> RunRegistry:
    registry = getattr(request.app.state, "run_registry", None)
    return registry if isinstance(registry, RunRegistry) else _FALLBACK_RUN_REGISTRY


def _settings(request: Request) -> Any:
    return getattr(request.app.state, "settings", None)


def _code_executor_url(request: Request) -> str:
    try:
        s = _settings(request)
        if s is not None:
            return s.code_executor_url.rstrip("/")
    except Exception:
        pass
    return "http://localhost:8888"


def _api_key(request: Request) -> str:
    s = _settings(request)
    return s.internal_api_key if s else ""


# ---------------------------------------------------------------------------
# Agent card
# ---------------------------------------------------------------------------


@router.get("/.well-known/agent-card")
async def agent_card_json(request: Request):
    """A2A-standard agent card endpoint."""
    base_url = str(request.base_url).rstrip("/")
    card = wotbot_agent_card(base_url=base_url)
    return JSONResponse(content=card.model_dump())


@router.get("/agent-card")
async def agent_card_legacy(request: Request):
    """Legacy agent card — delegates to the standard endpoint."""
    base_url = str(request.base_url).rstrip("/")
    card = wotbot_agent_card(base_url=base_url)
    return JSONResponse(content=card.model_dump())


# ---------------------------------------------------------------------------
# Artifact proxy — serve code-executor files through WoTBot
# ---------------------------------------------------------------------------


@router.get("/artifacts/{filename:path}")
async def proxy_artifact(filename: str, request: Request):
    """Proxy artifact files from the code executor.

    Public endpoint — no authentication required.
    Artifacts are files generated by the agent (plots, CSVs, etc.)
    and are served read-only.
    """
    if "/" in filename or "\\" in filename or ".." in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")

    executor_url = _code_executor_url(request)
    api_key = _api_key(request)
    result = await _fetch_artifact(executor_url, filename, api_key)
    if result is None:
        raise HTTPException(status_code=404, detail="Artifact not found")

    return Response(
        content=result["body"],
        media_type=result["content_type"],
        headers={"Content-Disposition": f'inline; filename="{filename}"'},
    )


_MAX_UPLOAD_SIZE = 50 * 1024 * 1024  # 50 MB
_ALLOWED_EXTENSIONS = {
    ".csv", ".json", ".xml", ".txt", ".log", ".parquet", ".feather", ".orc",
    ".xlsx", ".xls", ".ods", ".tsv", ".psv",
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg",
    ".html", ".htm", ".md", ".rst",
    ".zip", ".gz", ".bz2", ".xz", ".zst",
    ".npy", ".npz", ".pkl", ".pickle", ".joblib",
    ".h5", ".hdf5", ".nc", ".netcdf",
    ".yaml", ".yml", ".toml", ".cfg", ".ini",
    ".py", ".r", ".sql", ".sh",
}


@router.post("/upload")
async def upload_artifact(file: UploadFile, request: Request):
    """Upload a data file for the Python sandbox.

    Public endpoint — no authentication required.
    Only files with data-oriented extensions are accepted
    (see ``_ALLOWED_EXTENSIONS``).  Max size is 50 MB.

    Returns the filename that can be used with ``/api/a2a/artifacts/{filename}``
    and accessed in Python code via ``/tmp/code-executor-artifacts/{filename}``.
    """
    # Check extension
    ext = ""
    if file.filename and "." in file.filename:
        ext = "." + file.filename.rsplit(".", 1)[1].lower()
    if ext and ext not in _ALLOWED_EXTENSIONS:
        raise HTTPException(status_code=400, detail=f"File extension '{ext}' is not allowed")

    content = await file.read()
    if len(content) > _MAX_UPLOAD_SIZE:
        raise HTTPException(status_code=413, detail=f"File too large (max {_MAX_UPLOAD_SIZE // 1024 // 1024} MB)")

    executor_url = _code_executor_url(request)
    api_key = _api_key(request)

    # Try the code executor's upload endpoint first
    ext = ""
    if file.filename and "." in file.filename:
        ext = "." + file.filename.rsplit(".", 1)[1]
    filename = f"upload-{uuid4().hex}{ext}"

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.post(
                f"{executor_url}/upload",
                files={"file": (filename, content, file.content_type or "application/octet-stream")},
                headers={} if not api_key else {"Authorization": f"Bearer {api_key}"},
            )
            resp.raise_for_status()
            upload_data = resp.json()
            filename = upload_data.get("filename", filename)
    except Exception as exc:
        logger.warning("Code executor upload failed, storing locally: %s", exc)
        # Fallback: store in a local temp directory
        import tempfile
        local_dir = os.path.join(tempfile.gettempdir(), "a2a-uploads")
        os.makedirs(local_dir, exist_ok=True)
        local_path = os.path.join(local_dir, filename)
        with open(local_path, "wb") as f:
            f.write(content)
        # Also serve it via the proxy by adding a local-file fallback in _fetch_artifact
        logger.info("Saved uploaded file locally: %s (%d bytes)", local_path, len(content))

    return {"filename": filename, "size_bytes": len(content), "url": f"{str(request.base_url).rstrip('/')}/api/a2a/artifacts/{filename}"}


# ---------------------------------------------------------------------------
# Artifact fetching from the code executor
# ---------------------------------------------------------------------------


async def _fetch_artifact(
    executor_url: str, filename: str, api_key: str
) -> dict[str, Any] | None:
    safe = "/" not in filename and "\\" not in filename and ".." not in filename
    if not safe or not filename:
        return None
    url = f"{executor_url}/artifacts/{filename}"
    headers = {}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.get(url, headers=headers)
            resp.raise_for_status()
        body = resp.content
        return {"filename": filename, "body": body, "content_type": resp.headers.get("content-type", "application/octet-stream")}
    except httpx.HTTPStatusError as exc:
        if exc.response.status_code == 404:
            # Fallback: check local a2a-uploads directory
            import tempfile
            local_dir = os.path.join(tempfile.gettempdir(), "a2a-uploads")
            local_path = os.path.join(local_dir, filename)
            if os.path.isfile(local_path):
                with open(local_path, "rb") as f:
                    body = f.read()
                ct = "application/octet-stream"
                if filename.endswith(".csv"):
                    ct = "text/csv"
                elif filename.endswith(".json"):
                    ct = "application/json"
                elif filename.endswith(".png"):
                    ct = "image/png"
                return {"filename": filename, "body": body, "content_type": ct}
        logger.warning("Could not fetch artifact %s: %s", filename, exc)
        return None
    except Exception as exc:
        logger.warning("Could not fetch artifact %s: %s", filename, exc)
        return None


async def _collect_artifact_parts(events: list[Any], executor_url: str, api_key: str, base_url: str = "") -> list[Part]:
    """Scan events for artifact filenames, fetch from code executor, return as A2A Parts."""
    filenames: set[str] = set()
    for event in events:
        event_dict = _as_dict(event)
        if not event_dict:
            continue
        if event_dict.get("type") == "RAW":
            raw = event_dict.get("event") or {}
            if not isinstance(raw, dict):
                continue
            if raw.get("event") in ("on_tool_end", "on_chain_end"):
                output = raw.get("data", {}).get("output") or {}
                if not isinstance(output, dict):
                    continue
                content = output.get("content")
                if isinstance(content, str) and "artifacts" in content:
                    try:
                        parsed = json.loads(content)
                        if isinstance(parsed, dict):
                            for art in parsed.get("artifacts", []):
                                fn = art.get("filename") if isinstance(art, dict) else None
                                if isinstance(fn, str) and fn:
                                    filenames.add(fn)
                    except Exception:
                        pass

    if not filenames:
        return []

    results = await asyncio.gather(
        *[_fetch_artifact(executor_url, fn, api_key) for fn in filenames],
        return_exceptions=True,
    )
    parts: list[Part] = []
    for r in results:
        if not isinstance(r, dict):
            continue
        fn = r["filename"]
        body = r["body"]
        ct = r["content_type"]
        art_url = f"{base_url}/api/a2a/artifacts/{fn}" if base_url else ""
        if fn.endswith(".png"):
            parts.append(make_image_part(base64.b64encode(body).decode(), "image/png", url=art_url))
        elif fn.endswith((".html", ".json")):
            parts.append(Part(text="", mime_type="text/html", url=art_url, inline_data=body.decode("utf-8", errors="replace")))
        else:
            parts.append(make_image_part(base64.b64encode(body).decode(), ct, url=art_url))
    return parts


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _as_dict(obj: Any) -> dict | None:
    """Normalize an AG-UI event (Pydantic model / dict) to a plain dict."""
    if hasattr(obj, "model_dump"):
        return obj.model_dump()
    if hasattr(obj, "dict"):
        return obj.dict()
    if isinstance(obj, dict):
        return obj
    return None


def _build_graph_input(content_blocks: list[dict[str, Any]]) -> dict[str, Any]:
    """Build the LangGraph input for one user turn."""
    return {
        "messages": [
            {
                "id": f"msg-{uuid4().hex}",
                "role": "user",
                "content": content_blocks,
            }
        ]
    }


async def _stream_raw_events(
    graph: Any,
    registry: RunRegistry,
    thread_id: str,
    content_blocks: list[dict[str, Any]],
) -> AsyncGenerator[dict[str, Any], None]:
    """Run the graph for one turn, yielding RAW-wrapped LangGraph events.

    The A2A response builders below read ``on_chat_model_end``/``on_tool_end``
    payloads, so the graph's ``astream_events`` output is wrapped in the same
    ``{"type": "RAW", "event": ...}`` envelope the AG-UI runtime used to emit.
    The thread lock is shared with the chat routes so an external agent and the
    UI cannot drive the same thread at once.
    """
    config = {"configurable": {"thread_id": thread_id}}
    async with registry.thread_lock(thread_id):
        async for event in graph.astream_events(
            _build_graph_input(content_blocks),
            config=config,
            version="v2",
        ):
            yield {"type": "RAW", "event": event}


async def _upload_attachments(
    attachments: list[Attachment],
    executor_url: str,
    api_key: str,
    base_url: str,
) -> list[dict[str, Any]]:
    """Upload data attachments to the code executor; return extra content blocks.

    Images go to the vision LLM as-is.  Text/file attachments are uploaded to
    the code executor so the Python sandbox can access them, keeping large data
    out of the LLM context.
    """
    content_blocks: list[dict[str, Any]] = []
    for att in attachments:
        if att.type == "image" and att.data:
            content_blocks.append({"type": "image_url", "image_url": {"url": att.data}})
        elif att.type in ("text", "file") and att.data:
            try:
                data_bytes = base64.b64decode(att.data)
                ext = ".bin"
                if att.contentType == "text/csv":
                    ext = ".csv"
                elif att.contentType == "application/json":
                    ext = ".json"
                elif "text/" in att.contentType:
                    ext = ".txt"
                elif "xml" in att.contentType:
                    ext = ".xml"
                elif att.displayName and "." in att.displayName:
                    ext = "." + att.displayName.rsplit(".", 1)[1]

                filename = f"upload-{uuid4().hex}{ext}"
                async with httpx.AsyncClient(timeout=30.0) as client:
                    resp = await client.post(
                        f"{executor_url}/upload",
                        files={"file": (filename, data_bytes, att.contentType or "application/octet-stream")},
                        headers={} if not api_key else {"Authorization": f"Bearer {api_key}"},
                    )
                    resp.raise_for_status()
                    stored_filename = resp.json().get("filename", filename)

                label = att.displayName or stored_filename
                content_blocks.append({
                    "type": "text",
                    "text": (
                        f"[Uploaded file: {label}]\n"
                        f"The file is available at: {base_url}/api/a2a/artifacts/{stored_filename}\n"
                        f"To access it in Python use: /tmp/code-executor-artifacts/{stored_filename}\n"
                        f"Size: {len(data_bytes)} bytes"
                    ),
                })
            except Exception as exc:
                logger.warning("Failed to upload attachment to code executor: %s", exc)
                try:
                    decoded = base64.b64decode(att.data).decode("utf-8", errors="replace")
                    content_blocks.append({"type": "text", "text": f"[Attachment: {att.displayName or 'file'} ({att.contentType}) — upload failed, inline below]\n{decoded[:5000]}"})
                except Exception:
                    content_blocks.append({"type": "text", "text": f"[Attachment: {att.displayName or 'file'} ({att.contentType}) — {len(att.data)} base64 chars, upload failed]"})
    return content_blocks


def _extract_response_text(events: list[Any]) -> str:
    """Return the last non-JSON assistant text found in AG-UI events."""
    response_text = "(no response)"
    for event in events:
        ed = _as_dict(event)
        if not ed:
            continue
        if ed.get("type") == "RAW":
            raw = ed.get("event") or {}
            if raw.get("event") == "on_chat_model_end":
                output = raw.get("data", {}).get("output") or {}
                content = output.get("content") or ""
                if isinstance(content, str) and len(content) > 10:
                    if not (content.strip().startswith("{") and content.strip().endswith("}")):
                        response_text = content
    return response_text


def _build_task(run_id: str, thread_id: str, response_text: str, artifact_parts: list[Part]) -> Task:
    """Build a completed A2A Task with response text and artifacts."""
    task = Task(
        id=run_id,
        context_id=thread_id,
        status=TaskStatus(
            state=TaskState.COMPLETED,
            message=make_message(response_text, role=Role.ASSISTANT),
        ),
    )
    if artifact_parts:
        task.artifacts.append(
            Artifact(
                artifact_id=str(uuid4()),
                name="Agent Output",
                description="Visualizations and files generated by the agent",
                parts=artifact_parts,
            )
        )
    return task


def _parse_a2a_message(params: dict[str, Any]) -> tuple[str, str, list[Attachment]]:
    """Extract ``(message_text, context_id, attachments)`` from A2A ``params``."""
    message_text = ""
    context_id = ""
    attachments: list[Attachment] = []

    if "message" not in params:
        return message_text, context_id, attachments

    msg_data = params["message"]
    if isinstance(msg_data, dict):
        parts = msg_data.get("parts", [])
        if parts and isinstance(parts, list):
            for p in parts:
                if isinstance(p, dict) and p.get("text"):
                    message_text += p["text"] + "\n"
        context_id = msg_data.get("context_id", "")
        # Classify inline data by mime type
        for p in parts:
            if isinstance(p, dict) and p.get("inline_data"):
                mime = (p.get("mime_type") or "").lower()
                if mime.startswith("image/"):
                    attachments.append(Attachment(type="image", data=p["inline_data"], contentType=mime, displayName=p.get("file_name", "")))
                elif mime.startswith(("text/", "application/json", "application/csv", "application/xml")):
                    attachments.append(Attachment(type="text", data=p["inline_data"], contentType=mime, displayName=p.get("file_name", "")))
                else:
                    attachments.append(Attachment(type="file", data=p["inline_data"], contentType=mime, displayName=p.get("file_name", "")))
    elif isinstance(msg_data, str):
        message_text = msg_data

    return message_text.strip(), context_id, attachments


# ---------------------------------------------------------------------------
# Run the agent and produce a Task result
# ---------------------------------------------------------------------------


async def _run_agent(
    graph: Any,
    registry: RunRegistry,
    message_text: str,
    thread_id: str,
    run_id: str,
    executor_url: str,
    api_key: str,
    base_url: str = "",
    attachments: list[Attachment] | None = None,
) -> Task:
    """Run the WoTBot agent and return a completed Task with response text + artifacts.

    Data attachments (``text`` and ``file`` types) are **uploaded to the code
    executor** so they can be accessed by the Python sandbox.  The agent receives
    a message telling it the filename, avoiding large data in the LLM context.
    """
    content_blocks: list[dict[str, Any]] = [{"type": "text", "text": message_text}]
    if attachments:
        content_blocks.extend(await _upload_attachments(attachments, executor_url, api_key, base_url))

    events: list[Any] = []
    try:
        async for event in _stream_raw_events(graph, registry, thread_id, content_blocks):
            events.append(event)
    except asyncio.CancelledError:
        raise HTTPException(status_code=499, detail="Request cancelled")
    except Exception as exc:
        logger.exception("A2A run failed: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc))

    response_text = _extract_response_text(events)
    artifact_parts = await _collect_artifact_parts(events, executor_url, api_key, base_url)
    return _build_task(run_id, thread_id, response_text, artifact_parts)


# ---------------------------------------------------------------------------
# Streaming agent runner — yields SSE events
# ---------------------------------------------------------------------------


async def _run_agent_streaming(
    graph: Any,
    registry: RunRegistry,
    message_text: str,
    thread_id: str,
    run_id: str,
    executor_url: str,
    api_key: str,
    base_url: str = "",
    attachments: list[Attachment] | None = None,
) -> AsyncGenerator[str, None]:
    """Run the WoTBot agent and yield SSE ``TaskStatusUpdateEvent`` chunks.

    Each yielded string is a complete SSE message (``data: {{...}}\n\n``).
    The final event has ``final: true``.
    """
    content_blocks: list[dict[str, Any]] = [{"type": "text", "text": message_text}]
    if attachments:
        content_blocks.extend(await _upload_attachments(attachments, executor_url, api_key, base_url))

    def _sse(event: TaskStatusUpdateEvent) -> str:
        return f"data: {event.model_dump_json()}\n\n"

    # 1. Initial working event
    yield _sse(TaskStatusUpdateEvent(
        task_id=run_id,
        context_id=thread_id,
        status=TaskStatus(state=TaskState.WORKING),
        final=False,
    ))

    # 2. Run the agent — yield progress events inline
    events: list[Any] = []
    latest_text = ""

    try:
        async for event in _stream_raw_events(graph, registry, thread_id, content_blocks):
            events.append(event)
            ed = _as_dict(event)
            if not ed or ed.get("type") != "RAW":
                continue
            raw = ed.get("event") or {}
            if raw.get("event") == "on_chat_model_end":
                output = raw.get("data", {}).get("output") or {}
                content = output.get("content") or ""
                if isinstance(content, str) and len(content) > 10:
                    if not (content.strip().startswith("{") and content.strip().endswith("}")):
                        latest_text = content
                        yield _sse(TaskStatusUpdateEvent(
                            task_id=run_id,
                            context_id=thread_id,
                            status=TaskStatus(
                                state=TaskState.WORKING,
                                message=make_message(content, role=Role.ASSISTANT),
                            ),
                            final=False,
                        ))
            elif raw.get("event") == "on_tool_end":
                yield _sse(TaskStatusUpdateEvent(
                    task_id=run_id,
                    context_id=thread_id,
                    status=TaskStatus(
                        state=TaskState.WORKING,
                        message=make_message(f"[Tool completed: {raw.get('name', 'unknown')}]", role=Role.ASSISTANT),
                    ),
                    final=False,
                ))
    except asyncio.CancelledError:
        yield _sse(TaskStatusUpdateEvent(
            task_id=run_id, context_id=thread_id,
            status=TaskStatus(state=TaskState.CANCELED), final=True,
        ))
        return
    except Exception as exc:
        logger.exception("A2A stream run failed: %s", exc)
        yield _sse(TaskStatusUpdateEvent(
            task_id=run_id, context_id=thread_id,
            status=TaskStatus(
                state=TaskState.FAILED,
                message=make_message(str(exc), role=Role.ASSISTANT),
            ),
            final=True,
        ))
        return

    # 3. Build final Task with artifacts
    response_text = latest_text or _extract_response_text(events) or "(no response)"
    artifact_parts = await _collect_artifact_parts(events, executor_url, api_key, base_url)
    task = _build_task(run_id, thread_id, response_text, artifact_parts)

    # 4. Final event
    yield _sse(TaskStatusUpdateEvent(
        task_id=run_id, context_id=thread_id,
        status=task.status, final=True,
    ))


@router.post("/jsonrpc")
async def jsonrpc_endpoint(body: JSONRPCRequest, request: Request):
    """JSON-RPC 2.0 endpoint for the A2A protocol.

    Supported methods:
      - ``sendMessage`` — send a message, get a Task back
      - ``sendMessageStream`` — send a message, get a streaming TaskStatusUpdateEvent
    """
    graph = _agent_graph(request)
    if graph is None:
        return JSONResponse(
            content=JSONRPCResponse(id=body.id, error=JSONRPCError(code=-32000, message="Agent graph not ready")).model_dump(),
            status_code=503,
        )
    registry = _run_registry(request)

    if body.method == "sendMessage":
        return await _handle_send_message(body, graph, registry, request)
    elif body.method == "sendMessageStream":
        return await _handle_send_message_stream(body, graph, registry, request)
    else:
        return JSONResponse(
            content=JSONRPCResponse(id=body.id, error=JSONRPCError(code=-32601, message=f"Method not found: {body.method}")).model_dump(),
            status_code=400,
        )


async def _handle_send_message(
    body: JSONRPCRequest, graph: Any, registry: RunRegistry, request: Request
) -> JSONResponse:
    """Handle a sendMessage JSON-RPC call."""
    executor_url = _code_executor_url(request)
    api_key = _api_key(request)
    message_text, context_id, attachments = _parse_a2a_message(body.params or {})

    if not message_text:
        return JSONResponse(
            content=JSONRPCResponse(id=body.id, error=JSONRPCError(code=-32602, message="No message text provided")).model_dump(),
            status_code=400,
        )

    thread_id = context_id or f"a2a-{uuid4().hex}"
    run_id = uuid4().hex
    base_url = str(request.base_url).rstrip("/")

    try:
        task = await _run_agent(graph, registry, message_text, thread_id, run_id, executor_url, api_key, base_url, attachments)
    except HTTPException as exc:
        task = Task(
            id=run_id,
            context_id=thread_id,
            status=TaskStatus(state=TaskState.FAILED, message=make_message(str(exc.detail), role=Role.ASSISTANT)),
        )

    result = SendMessageResult(task=task)
    return JSONResponse(
        content=JSONRPCResponse(id=body.id, result=result.model_dump()).model_dump(),
    )


async def _handle_send_message_stream(
    body: JSONRPCRequest, graph: Any, registry: RunRegistry, request: Request
) -> StreamingResponse:
    """Handle a sendMessageStream call — returns a SSE streaming response.

    Yields ``TaskStatusUpdateEvent`` chunks as the agent runs.
    """
    executor_url = _code_executor_url(request)
    api_key = _api_key(request)
    message_text, context_id, attachments = _parse_a2a_message(body.params or {})

    if not message_text:
        error_event = TaskStatusUpdateEvent(
            task_id="",
            status=TaskStatus(
                state=TaskState.FAILED,
                message=make_message("No message text provided", role=Role.ASSISTANT),
            ),
            final=True,
        )
        return StreamingResponse(
            content=f"data: {error_event.model_dump_json()}\n\n",
            media_type="text/event-stream",
            headers={"X-ACCEPTED": "text/event-stream"},
        )

    thread_id = context_id or f"a2a-{uuid4().hex}"
    run_id = uuid4().hex
    base_url = str(request.base_url).rstrip("/")

    return StreamingResponse(
        content=_run_agent_streaming(graph, registry, message_text, thread_id, run_id, executor_url, api_key, base_url, attachments),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


# ---------------------------------------------------------------------------
# Backward-compatible simple message endpoint
# ---------------------------------------------------------------------------


@router.post("/message")
async def post_message(
    body: A2AMessage,
    request: Request,
    _ok: Any = None,
):
    """Legacy simple message endpoint.  Returns the same format as before."""
    graph = _agent_graph(request)
    if graph is None:
        raise HTTPException(status_code=503, detail="Agent graph not ready")
    registry = _run_registry(request)

    executor_url = _code_executor_url(request)
    api_key = _api_key(request)
    base_url = str(request.base_url).rstrip("/")
    thread_id = body.threadId or f"embed-ephemeral-{uuid4().hex}"
    run_id = uuid4().hex

    try:
        task = await _run_agent(graph, registry, body.message, thread_id, run_id, executor_url, api_key, base_url, body.attachments or None)
    except HTTPException as exc:
        raise exc

    # Collect events for backward compat
    events = []
    if task.status.message:
        for p in task.status.message.parts:
            if p.text:
                events.append({"type": "text", "content": p.text})
    for art in task.artifacts:
        for p in art.parts:
            events.append({
                "type": "A2A_ARTIFACTS",
                "artifacts": [{
                    "filename": art.artifact_id,
                    "kind": "image" if "image" in p.mime_type else "plotly",
                    "media_type": p.mime_type,
                    "base64": p.inline_data if p.inline_data else "",
                }],
            })

    return {
        "ok": task.status.state == TaskState.COMPLETED,
        "thread_id": thread_id,
        "run_id": run_id,
        "events": events,
        "task": task.model_dump(),
    }
