"""Shared constants for code execution sessions."""

RESULT_POLL_INTERVAL_SECONDS = 0.1
SESSION_WATCHDOG_GRACE_SECONDS = 5
MAX_STDOUT_CHARS = 2000

SENSITIVE_ENV_VARS = (
    "INIT_ADMIN_TOKEN",
    "INTERNAL_API_KEY",
    "OPENAI_EMBEDDING_API_KEY",
    "WOT_RUNTIME_API_TOKEN",
    "WOT_RUNTIME_REGISTRY_TOKEN",
    "OPENAI_API_KEY",
)
