from collections.abc import Iterator
from functools import lru_cache

import psycopg
from psycopg.rows import DictRow, dict_row
from psycopg_pool import ConnectionPool
from sqlalchemy import create_engine
from sqlalchemy.engine import Engine
from sqlalchemy.orm import Session, sessionmaker

from copilot.core.config import get_settings

DatabaseConnection = psycopg.Connection[DictRow]


def psycopg_conninfo(database_url: str) -> str:
    if database_url.startswith("postgresql+psycopg://"):
        return database_url.replace("postgresql+psycopg://", "postgresql://", 1)
    return database_url


def sqlalchemy_url(database_url: str) -> str:
    if database_url.startswith("postgresql://"):
        return database_url.replace("postgresql://", "postgresql+psycopg://", 1)
    return database_url


@lru_cache()
def get_connection_pool() -> ConnectionPool[DatabaseConnection]:
    return ConnectionPool(
        conninfo=psycopg_conninfo(get_settings().DATABASE_URL),
        kwargs={"row_factory": dict_row},
        min_size=1,
        max_size=10,
        open=True,
    )


@lru_cache()
def get_sqlalchemy_engine() -> Engine:
    return create_engine(sqlalchemy_url(get_settings().DATABASE_URL), pool_pre_ping=True)


@lru_cache()
def get_session_factory() -> sessionmaker[Session]:
    return sessionmaker(bind=get_sqlalchemy_engine(), expire_on_commit=False)


def get_connection() -> Iterator[DatabaseConnection]:
    """FastAPI dependency yielding a pooled Postgres connection."""
    with get_connection_pool().connection() as connection:
        yield connection


def get_session() -> Iterator[Session]:
    """FastAPI dependency yielding a SQLAlchemy ORM session."""
    with get_session_factory() as session:
        yield session


def init_db(pool: ConnectionPool[DatabaseConnection] | None = None) -> None:
    """Create or update the Postgres schema owned by the copilot service."""
    connection_pool = pool or get_connection_pool()
    with connection_pool.connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS api_keys (
                    id TEXT PRIMARY KEY,
                    key_prefix TEXT NOT NULL,
                    key_hash TEXT NOT NULL UNIQUE,
                    name TEXT NOT NULL,
                    scopes JSONB NOT NULL DEFAULT '[]'::jsonb,
                    user_id TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    expires_at TIMESTAMPTZ,
                    last_used_at TIMESTAMPTZ,
                    is_active BOOLEAN NOT NULL DEFAULT true
                );

                CREATE INDEX IF NOT EXISTS ix_api_keys_key_hash
                    ON api_keys(key_hash);

                CREATE TABLE IF NOT EXISTS things (
                    id TEXT PRIMARY KEY,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL DEFAULT '',
                    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
                    document JSONB NOT NULL,
                    document_hash TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                );

                CREATE TABLE IF NOT EXISTS thing_credentials (
                    id TEXT PRIMARY KEY,
                    thing_id TEXT NOT NULL,
                    security_name TEXT NOT NULL,
                    scheme TEXT NOT NULL,
                    credentials JSONB NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    CONSTRAINT uq_thing_security UNIQUE (thing_id, security_name)
                );

                CREATE TABLE IF NOT EXISTS thing_event_outbox (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_type TEXT NOT NULL,
                    thing_id TEXT NOT NULL,
                    event_hash TEXT NOT NULL DEFAULT '',
                    payload_json JSONB NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    published_at TIMESTAMPTZ,
                    attempt_count INTEGER NOT NULL DEFAULT 0,
                    last_error TEXT NOT NULL DEFAULT ''
                );

                CREATE INDEX IF NOT EXISTS idx_thing_event_outbox_pending
                    ON thing_event_outbox(published_at, id);

                CREATE TABLE IF NOT EXISTS jobs (
                    id TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                    thread_id TEXT NOT NULL,
                    job_type TEXT NOT NULL DEFAULT 'prompt',
                    prompt TEXT,
                    analysis_code TEXT,
                    enabled BOOLEAN NOT NULL DEFAULT true,
                    trigger_type TEXT NOT NULL,
                    run_at TEXT,
                    interval_seconds INTEGER,
                    next_run_at TEXT,
                    thing_id TEXT,
                    event_name TEXT,
                    subscription_id TEXT,
                    subscription_input_json TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    last_run_at TEXT,
                    last_error TEXT,
                    last_response TEXT,
                    run_count INTEGER NOT NULL DEFAULT 0,
                    last_fetch_value TEXT
                );

                CREATE INDEX IF NOT EXISTS idx_jobs_due
                    ON jobs(trigger_type, enabled, next_run_at);

                CREATE INDEX IF NOT EXISTS idx_jobs_subscription
                    ON jobs(subscription_id, enabled);
                """
            )
        connection.commit()
