from collections.abc import Iterator
from functools import lru_cache

import psycopg
from psycopg.rows import DictRow, dict_row
from psycopg_pool import ConnectionPool
from sqlalchemy import create_engine
from sqlalchemy.engine import Engine
from sqlalchemy.orm import Session, sessionmaker

from copilot.core.config import get_settings

DatabaseConnection = psycopg.Connection[DictRow]


def psycopg_conninfo(database_url: str) -> str:
    if database_url.startswith("postgresql+psycopg://"):
        return database_url.replace("postgresql+psycopg://", "postgresql://", 1)
    return database_url


def sqlalchemy_url(database_url: str) -> str:
    if database_url.startswith("postgresql://"):
        return database_url.replace("postgresql://", "postgresql+psycopg://", 1)
    return database_url


@lru_cache()
def get_connection_pool() -> ConnectionPool[DatabaseConnection]:
    return ConnectionPool(
        conninfo=psycopg_conninfo(get_settings().DATABASE_URL),
        kwargs={"row_factory": dict_row},
        min_size=1,
        max_size=10,
        open=True,
    )


@lru_cache()
def get_sqlalchemy_engine() -> Engine:
    return create_engine(sqlalchemy_url(get_settings().DATABASE_URL), pool_pre_ping=True)


@lru_cache()
def get_session_factory() -> sessionmaker[Session]:
    return sessionmaker(bind=get_sqlalchemy_engine(), expire_on_commit=False)


def get_connection() -> Iterator[DatabaseConnection]:
    """FastAPI dependency yielding a pooled Postgres connection."""
    with get_connection_pool().connection() as connection:
        yield connection


def get_session() -> Iterator[Session]:
    """FastAPI dependency yielding a SQLAlchemy ORM session."""
    with get_session_factory() as session:
        yield session


def init_db(pool: ConnectionPool[DatabaseConnection] | None = None) -> None:
    """Create or update the Postgres schema owned by the copilot service."""
    connection_pool = pool or get_connection_pool()
    vector_dimensions = get_settings().SEARCH_VECTOR_DIMENSIONS
    with connection_pool.connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                f"""
                CREATE EXTENSION IF NOT EXISTS vector;

                CREATE TABLE IF NOT EXISTS api_keys (
                    id TEXT PRIMARY KEY,
                    key_prefix TEXT NOT NULL,
                    key_hash TEXT NOT NULL UNIQUE,
                    name TEXT NOT NULL,
                    scopes JSONB NOT NULL DEFAULT '[]'::jsonb,
                    user_id TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    expires_at TIMESTAMPTZ,
                    last_used_at TIMESTAMPTZ,
                    is_active BOOLEAN NOT NULL DEFAULT true
                );

                CREATE INDEX IF NOT EXISTS ix_api_keys_key_hash
                    ON api_keys(key_hash);

                CREATE TABLE IF NOT EXISTS things (
                    id TEXT PRIMARY KEY,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL DEFAULT '',
                    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
                    document JSONB NOT NULL,
                    document_hash TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                );

                CREATE TABLE IF NOT EXISTS thing_credentials (
                    id TEXT PRIMARY KEY,
                    thing_id TEXT NOT NULL,
                    security_name TEXT NOT NULL,
                    scheme TEXT NOT NULL,
                    credentials JSONB NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    CONSTRAINT uq_thing_security UNIQUE (thing_id, security_name)
                );

                CREATE TABLE IF NOT EXISTS thing_event_outbox (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_type TEXT NOT NULL,
                    thing_id TEXT NOT NULL,
                    event_hash TEXT NOT NULL DEFAULT '',
                    payload_json JSONB NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    published_at TIMESTAMPTZ,
                    attempt_count INTEGER NOT NULL DEFAULT 0,
                    last_error TEXT NOT NULL DEFAULT ''
                );

                CREATE INDEX IF NOT EXISTS idx_thing_event_outbox_pending
                    ON thing_event_outbox(published_at, id);

                CREATE TABLE IF NOT EXISTS search_index_chunks (
                    chunk_id TEXT PRIMARY KEY,
                    thing_id TEXT NOT NULL,
                    page_content TEXT NOT NULL,
                    metadata_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    embedding vector({vector_dimensions}) NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                );

                CREATE INDEX IF NOT EXISTS idx_search_index_chunks_thing_id
                    ON search_index_chunks(thing_id);

                CREATE INDEX IF NOT EXISTS idx_search_index_chunks_embedding_hnsw
                    ON search_index_chunks
                    USING hnsw (embedding vector_cosine_ops);

                CREATE TABLE IF NOT EXISTS jobs (
                    id TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                    created_from_thread_id TEXT NOT NULL,
                    job_thread_id TEXT NOT NULL UNIQUE,
                    action_kind TEXT NOT NULL DEFAULT 'prompt',
                    prompt TEXT,
                    analysis_code TEXT,
                    enabled BOOLEAN NOT NULL DEFAULT true,
                    trigger_kind TEXT NOT NULL,
                    schedule_kind TEXT,
                    run_at TIMESTAMPTZ,
                    interval_seconds INTEGER,
                    next_run_at TIMESTAMPTZ,
                    thing_id TEXT,
                    event_name TEXT,
                    subscription_id TEXT,
                    subscription_input JSONB,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
                    last_run_id TEXT,
                    last_run_at TIMESTAMPTZ,
                    last_run_status TEXT,
                    last_error TEXT,
                    last_response TEXT,
                    run_count INTEGER NOT NULL DEFAULT 0,
                    active_run_id TEXT,
                    active_run_started_at TIMESTAMPTZ,
                    active_run_source TEXT,
                    waiting_question TEXT,
                    CONSTRAINT ck_jobs_action_kind
                        CHECK (action_kind IN ('prompt', 'analysis')),
                    CONSTRAINT ck_jobs_trigger_kind
                        CHECK (trigger_kind IN ('time', 'event')),
                    CONSTRAINT ck_jobs_schedule_kind
                        CHECK (schedule_kind IS NULL OR schedule_kind IN ('once', 'interval')),
                    CONSTRAINT ck_jobs_last_run_status
                        CHECK (
                            last_run_status IS NULL
                            OR last_run_status IN (
                                'running',
                                'succeeded',
                                'failed',
                                'waiting_for_input',
                                'cancelled',
                                'skipped'
                            )
                        ),
                    CONSTRAINT ck_jobs_active_run_source
                        CHECK (
                            active_run_source IS NULL
                            OR active_run_source IN ('manual', 'time', 'event')
                        )
                );

                CREATE TABLE IF NOT EXISTS job_runs (
                    id TEXT PRIMARY KEY,
                    job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
                    job_thread_id TEXT NOT NULL,
                    source TEXT NOT NULL,
                    status TEXT NOT NULL,
                    trigger_payload JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    result JSONB,
                    error TEXT,
                    response_text TEXT,
                    started_at TIMESTAMPTZ NOT NULL,
                    finished_at TIMESTAMPTZ,
                    created_at TIMESTAMPTZ NOT NULL,
                    CONSTRAINT ck_job_runs_source
                        CHECK (source IN ('manual', 'time', 'event')),
                    CONSTRAINT ck_job_runs_status
                        CHECK (
                            status IN (
                                'running',
                                'succeeded',
                                'failed',
                                'waiting_for_input',
                                'cancelled',
                                'skipped'
                            )
                        )
                );

                CREATE INDEX IF NOT EXISTS idx_jobs_due
                    ON jobs(trigger_kind, enabled, next_run_at);

                CREATE INDEX IF NOT EXISTS idx_jobs_created_from_thread
                    ON jobs(created_from_thread_id);

                CREATE INDEX IF NOT EXISTS idx_jobs_subscription
                    ON jobs(subscription_id, enabled);

                CREATE INDEX IF NOT EXISTS idx_job_runs_job_started
                    ON job_runs(job_id, started_at);
                """
            )
        connection.commit()
